baseURL = 'https://djangobeeprints.com/'
languageCode = 'en-us'
title = 'Djangobee Prints'
enableRobotsTXT = true
enableGitInfo = false

[params]
  description = 'Technology Integration in Elementary Music Education'
  author = 'Djangobee Prints'

  # Social media (add your handles)
  [params.social]
    twitter = ''  # Add your Twitter/X URL if you have one

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[taxonomies]
  tag = 'tags'
  category = 'categories'

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menu.main]]
    name = 'About Me'
    pageRef = '/about'
    weight = 2
  [[menu.main]]
    name = 'Technology Guides'
    pageRef = '/tech-guides'
    weight = 3
  [[menu.main]]
    name = 'Educational Thoughts'
    pageRef = '/thoughts'
    weight = 4
  [[menu.main]]
    name = 'Resources'
    pageRef = '/resources'
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
